### ISSUE TITLE
Peer to peer code review for Capstone project (22/09/2022)

### ISSUE THREAD

**Issue by tashisrael** [teke85/Lilayi_Lodge#2]
Hi @teke85 
Good Job so far 👏🏽 

# Acknowledgements

- The code meets its requirements
- No linter errors
- Clean code

# Issues
- Increase font sizes of your first section on the home page
- Add links to some of your nav items
- [Optional] Add screenshots of your pages to Readme file

**Comment by teke85** [comment]
Hi @tashisrael Thank you for your code review. I will make the suggested changes to improve the website.
